### ISSUE TITLE
Simpler Self Host

### ISSUE THREAD

**Issue by zhdenny** [unsearchapp/unsearch#3]
Just some ideas to make self hosting this easier and similar to most other self host apps out there:

1. Developer-managed docker image available through dockerhub or similar docker image repo. Most mainstream self host apps do not require users to got clone their repo and build the docker image themselves.
2. Instead of having users build their own extensions, it would be so much easier if the official extension had a setting to declare the URL and any necessary access credentials to the self host instance.

Again, just some ideas to make this whole thing a bit more friendly to the casual self hoster.

**Comment by dr-alberto** [comment]
Thanks for letting me know. 

- Most likely I will add the option to select a custom backend in the official extension directly so that there is no need to build the extensions again.

- There are different services that I manage through docker-compose.prod.yml, at the moment both frontend and backend images are [published](https://github.com/orgs/unsearchapp/packages). Apart from this two services, migrations are applied on the connected database and an nginx reverse proxy is deployed. At the moment it is necessary to use domains with SSL to be able to connect the extension (at least in Firefox). I will think about how I can simplify the self-hosting in the next version.

**Comment by zhdenny** [comment]
This is great! I had no idea you have frontend and backend images published. I guess I didn't see how to use these in your installation instructions. The install instructions seemed more geared towards building your own docker image from the github repo.

Look forward to seeing these improvements. I've been using an ancient browser sync extension for years and am in need of a replacement.

**Comment by dr-alberto** [comment]
Yeah, I will review the documentation to see how to improve it as well.

**Comment by dr-alberto** [comment]
Closing this issue. In the next release, I plan to remove the need for using a domain when self-hosting and instead allow the extension to connect directly to the machine's IP. I think this will make self-hosting even easier.
